### ISSUE TITLE
Error after upload

### ISSUE THREAD

**Issue by NamelessJuan** [lloydsargent/BlackRaccoon#29]
after the upload an error occur when the timeout expires this error happens even when im already in the other screen. This happens in ios6 and ios7.

[__NSDate release]: message sent to deallocated instance 0xecedba0. 

![screenshot_23_9_13_10_06_pm](https://f.cloud.github.com/assets/5519359/1191884/8d009bf6-2459-11e3-94fc-ef7f326401ff.png)

**Comment by davegl1234** [comment]
Hi, this is a really useful ftp program, thanks.

I am have one issue however. I am iterating though a load of files stored locally on a device, and comparing the date modified with the date modified on a server (to replace if necessary). However, the UTC date returned by kCFFTPResourceModDate is an hour out!? It reports an hour earlier than it should. I've checked the server and it is at the correct time. 

E.g The files were last update on the device at 13.30 GMT BST (12.30 UTC). I then update the files on the server at 14.00 GMT BST (13.00 UTC). When I compare the files, the date of the files on the device are 12.30 UTC, but kCFFTPResourceModDate reports that the files on the server were last modified at 12.00 UTC. What is happening here? Is there anything I can do?

Thanks
