### ISSUE TITLE
Unable to complete two download requests in a row.

### ISSUE THREAD

**Issue by ScarletBasel** [lloydsargent/BlackRaccoon#3]
if I ask for 2 download in a row, only the first request works correctly, the rest just give back 0 bytes or a timeout error occurs. for example the code below will not work, it just times out after the first download.

   self.read1 = [[BRRequestDownload alloc] init];
    self.read1.delegate = self;
    self.read1.path = @"/FTPTest/pic1.png";
    self.read1.username = @"username;
    self.read1.hostname = @"host.com";
    self.read1.password = @"password";

```
self.read2 = [[BRRequestDownload alloc] init];
self.read2.delegate = self;
self.read2.path = @"/FTPTest/pic2.png";
self.read2.username = @"username;
self.read2.hostname = @"host.com";
self.read2.password = @"password";
```

   [self.read1 start];
    [self.read2 start];

-(void)requestCompleted:(BRRequest *)request{

```
  NSLog(@"size = %i",[[(BRRequestDownload *)request receivedData] length]);
```

  }

**Comment by kpragati** [comment]
Hi I am using White Raccoon for uploading file But I got "[WRRequestListDirectory stream:handleEvent:] [Line 982] Unknown error!" this error. Can you please guide me how to remove that error. thank you.
