### ISSUE TITLE
how to rename a file

### ISSUE THREAD

**Issue by zhengying** [lloydsargent/BlackRaccoon#51]
No rename operation support ?

**Comment by lloydsargent** [comment]
This was not a part of BlackRaccoon’s design. However, source is provided, so feel free to add rename support.

**Comment by NirmitDagly** [comment]
can you please share source with me that How can I rename file?

**Comment by lloydsargent** [comment]
The source to Black Raccoon is provided to you. If YOU want rename support, then YOU may add it. Feel free to share with everyone.
