### ISSUE TITLE
kCFFTPResourceModDate reporting wrong date

### ISSUE THREAD

**Issue by davegl1234** [lloydsargent/BlackRaccoon#52]
Hi, this is a really useful ftp program, thanks.

I am have one issue however. I am iterating though a load of files stored locally on a device, and comparing the date modified with the date modified on a server (to replace if necessary). However, the UTC date returned by kCFFTPResourceModDate is an hour out!? It reports an hour earlier than it should. I've checked the server and it is at the correct time.

E.g The files were last update on the device at 13.30 GMT BST (12.30 UTC). I then update the files on the server at 14.00 GMT BST (13.00 UTC). When I compare the files, the date of the files on the device are 12.30 UTC, but kCFFTPResourceModDate reports that the files on the server were last modified at 12.00 UTC. What is happening here? Is there anything I can do?

Update - using an NSURLRequest and 'objectForKey:@"Last-Modified"' on the response, I do get the correct date (13.00 UTC in the example above)..so it must be some sort of bug?

Thanks

**Comment by lloydsargent** [comment]
BlackRaccoon uses the routines from Apple.

There has been indications from Apple that these routines will be deprecated and eliminated (when? they don’t tell me).

If there is an error in the Mod date it comes from Apple’s code - I am pretty sure I do not touch the date. It is conceivable that NSURLRequest does some extra work, assuring that the dates are correct (how? why? again, they don’t tell me)

I’m sorry I’m unable to help you.

Cheers,

Lloyd
