### ISSUE TITLE
EXC_BAD_ACCESS address=0xb17d7357

### ISSUE THREAD

**Issue by SebOH123** [lloydsargent/BlackRaccoon#54]
Hello,

Having issues with BRRequestListDirectory crashing on '@implementation BRRequestListDirectory' when loading - image attached. I get the error after about the third time it is called - the code is in a 30 second loop.

Code below. Running iOS 9, on XCODE 7 BETA 3.

listDir = [[BRRequestListDirectory alloc] initWithDelegate:self];
listDir.path = @"/***_";
listDir.hostname = @"**__";
listDir.username = @"_**_";
listDir.password = @"**_*";
[listDir start];

<img width="714" alt="screen shot 2015-07-26 at 5 32 25 pm" src="https://cloud.githubusercontent.com/assets/6457521/8892956/6ec71cea-33bc-11e5-87b8-74627f9ef56b.png">

**Comment by lloydsargent** [comment]
Please note: I do not test against beta versions of iOS.

If the error occurs with the test rig as well, I will look into it.
