### ISSUE TITLE
Example of queue to Upload and Download Data from FTP

### ISSUE THREAD

**Issue by NirmitDagly** [lloydsargent/BlackRaccoon#56]
Hello,
Can anyone tell me how to use queue to upload and download files from FTP using black raccoon? I've tried to search this repository as well as google to find the example but have not get any success. So, can you help me out by showing me how I can use queue effectively? 

Thanks in advance.

**Comment by lloydsargent** [comment]
In the documentation I have said:

**"A function to queue requests has been left in the code, but has not been tested. As this is not a normal FTP function, the user should assume it is deprecated and will be removed from future releases."**

FTP isn't really designed for queuing as there are MANY errors that can happen that give the same error number. This is why queues are DEPRECATED and untested.

If you want to ask this kind of question, please ask it on sites like StackOverflow.

"Issues" is not an area to ask "how do I program using BlackRaccoon".

Please use Issues **ONLY** for bugs and errors.
