### ISSUE TITLE
Upload an image. Part of the image is grayed out

### ISSUE THREAD

**Issue by ghost** [lloydsargent/BlackRaccoon#61]
Thank you for a great solution for FTP upload. It really helps.
the problem is that the uploaded image is partly grayed out, like it is not fully loaded. Updating the folder contents does not help.
![fb75r](https://cloud.githubusercontent.com/assets/3919263/14084820/563a3bdc-f525-11e5-9576-85bf892bfee8.jpg)

**Comment by lloydsargent** [comment]
You can **never load a very large image all into memory** and successfully transfer. I have reiterated this multiple times. You must transfer it from a **file** piece by piece. Many people, including myself, have discovered this.

There is something on the **Apple FTP routines** that prevents this. No, I don’t know why. However, for it to work correctly (for anything over about 2 megabytes) you need to transfer from a **file** a small section at a time, and transfer it using:
- (NSData *) requestDataToSend: (BRRequestUpload *) request

You will return a SMALL PART (a few kilobytes) of the large file. That is the point of it. You return sections of the file bit by bit. This is the only way you can send a large file to an FTP server.

This is the **only way** to successfully transfer a large file.

**Comment by ghost** [comment]
Thank you for answering!
I will try to do it this way:
- (NSData *)requestDataToSend:(BRRequestUpload *)request {
  //load in small chunks 10kb
  
  if (_dataToUpload) {
      if (request.totalBytesSent < _dataToUpload.length) {
          return [_dataToUpload subdataWithRange:NSMakeRange(request.totalBytesSent, MIN(10000, (_dataToUpload.length - request.totalBytesSent)))];
      }
  }
  
  // Done uploading
  _dataToUpload = nil;
  return nil;
  }

**Comment by ghost** [comment]
I have tried this. But for some reason the image sometimes is still grayed out. Is there a way to delete the image if it was not uploaded properly?

**Comment by lloydsargent** [comment]
BlackRaccoon should allow you to delete a file up to iOS 7 at which point Apple’s delete function was deprecated.

As I indicated in the documentation, if you need full FTP functionality, it is better to go with a full FTP package. This was designed using Apple’s functions that they have indicated they will eventually remove.
